USE [master]
GO

/****** Object:  Database [MyCheerBook]    Script Date: 12/14/2013 12:47:38 PM ******/
DROP DATABASE [MyCheerBook]
GO

/****** Object:  Database [MyCheerBook]    Script Date: 12/14/2013 12:47:38 PM ******/
CREATE DATABASE [MyCheerBook]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'MyCheerBook', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\MyCheerBook.mdf' , SIZE = 3136KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'MyCheerBook_log', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\MyCheerBook_log.ldf' , SIZE = 832KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [MyCheerBook] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MyCheerBook].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [MyCheerBook] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [MyCheerBook] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [MyCheerBook] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [MyCheerBook] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [MyCheerBook] SET ARITHABORT OFF 
GO

ALTER DATABASE [MyCheerBook] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [MyCheerBook] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [MyCheerBook] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [MyCheerBook] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [MyCheerBook] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [MyCheerBook] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [MyCheerBook] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [MyCheerBook] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [MyCheerBook] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [MyCheerBook] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [MyCheerBook] SET  ENABLE_BROKER 
GO

ALTER DATABASE [MyCheerBook] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [MyCheerBook] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [MyCheerBook] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [MyCheerBook] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [MyCheerBook] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [MyCheerBook] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [MyCheerBook] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [MyCheerBook] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [MyCheerBook] SET  MULTI_USER 
GO

ALTER DATABASE [MyCheerBook] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [MyCheerBook] SET DB_CHAINING OFF 
GO

ALTER DATABASE [MyCheerBook] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [MyCheerBook] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [MyCheerBook] SET  READ_WRITE 
GO


